## Coffee Production Prediction

Given *data about coffee*, let's try to predict the **average production** of coffee in a given country. 

We will use a random forest regression model to make our predictions. 

Data source: https://www.kaggle.com/datasets/yamaerenay/ico-coffee-dataset-worldwide

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor

In [2]:
df_paths = [
    "domestic-consumption.csv",
    "exports-calendar-year.csv",
    "exports-crop-year.csv",
    "gross-opening-stocks.csv",
    "total-production.csv"
]

In [3]:
dfs = [pd.read_csv(df_path) for df_path in df_paths]

### Preprocessing

In [12]:
def get_means(df):
    df = df.copy()
    countries = df[df.columns[0]]
    means = df.mean(axis=1, numeric_only=True)
    df = pd.concat([countries, means], axis=1)
    df.columns = ['country', countries.name]
    return df

In [13]:
get_means(dfs[0])

                             country  domestic_consumption
0                             Angola             25.689655
1   Bolivia (Plurinational State of)             41.103448
2                             Brazil          15234.310345
3                            Burundi              1.891966
4                            Ecuador            214.137931
5                          Indonesia           2662.137931
6                         Madagascar            325.405724
7                             Malawi              1.310345
8                   Papua New Guinea              2.004828
9                           Paraguay             19.482759
10                              Peru            222.413793
11                            Rwanda              1.195379
12                       Timor-Leste              0.152069
13                          Zimbabwe              4.802276
14                             Congo              2.977034
15                              Cuba            213.244828
16                Dominican Republic            356.438724
17                             Haiti            333.275862
18                       Philippines           1501.310345
19                          Tanzania             40.646586
20                            Zambia              0.570069
21                             Benin              0.000000
22                          Cameroon             79.787897
23          Central African Republic             13.560000
24                          Colombia           1388.097669
25                        Costa Rica            370.238621
26                     CÃ´te d'Ivoire            224.850655
27      Democratic Republic of Congo            200.000000
28                       El Salvador            229.725310
29                 Equatorial Guinea              0.000000
30                          Ethiopia           2529.034483
31                             Gabon              0.628241
32                             Ghana              5.661379
33                         Guatemala            326.034483
34                            Guinea             48.120690
35                            Guyana              4.978759
36                          Honduras            259.109586
37                             India           1153.137931
38                           Jamaica             10.429897
39                             Kenya             52.241379
40  Lao People's Democratic Republic             85.379310
41                           Liberia              4.793103
42                            Mexico           1749.517241
43                             Nepal              0.000000
44                         Nicaragua            165.000172
45                           Nigeria             39.275862
46                            Panama             68.331586
47                      Sierra Leone              5.620690
48                         Sri Lanka             32.298862
49                          Thailand            669.310345
50                              Togo              1.236793
51                 Trinidad & Tobago             11.775862
52                            Uganda            154.928966
53                         Venezuela           1327.337931
54                          Viet Nam           1016.050759
55                             Yemen             67.689655

In [16]:
def make_df(dfs):
    # Process all DataFrames into one DataFrame
    processed_dfs = []
    for df in dfs:
        processed_dfs.append(get_means(df))
    
    # Merge DataFrames
    df = processed_dfs[0]

    for i in range(1, len(processed_dfs)):
        df = df.merge(processed_dfs[i], on='country')

    return df

In [17]:
data = make_df(dfs)
data

,country,domestic_consumption,exports,exports_crop_year,gross_opening_stocks,total_production
0,Angola,25.689655,24.115531,23.187083,42.068966,45.256048
1,Bolivia (Plurinational State of),41.103448,78.384152,76.904748,7.237931,116.146128
2,Brazil,15234.310345,25706.195606,25919.128803,23213.206897,41067.783976
3,Burundi,1.891966,363.186423,356.056321,48.979690,350.172424
4,Ecuador,214.137931,1115.800914,1105.434110,108.592069,1076.504352
5,Indonesia,2662.137931,5878.047357,5879.061059,690.114655,8452.302438
6,Madagascar,325.405724,289.048949,280.822603,87.587000,587.719424
7,Malawi,1.310345,47.247465,46.095669,4.896552,46.716359
8,Papua New Guinea,2.004828,1015.455512,1015.019583,55.757928,1010.334755
9,Paraguay,19.482759,25.757542,20.850776,36.379310,34.678362
10,Peru,222.413793,2688.290420,2693.919669,107.769345,2923.816221
11,Rwanda,1.195379,316.250499,312.973890,15.106690,309.893407
12,Timor-Leste,0.152069,35.083247,35.722397,0.000000,35.874466
13,Zimbabwe,4.802276,78.112883,76.360955,18.070241,75.645990
14,Congo,2.977034,1.341862,1.283931,1.931034,3.847172
15,Cuba,213.244828,63.499287,61.241072,78.068966,201.634176
16,Dominican Republic,356.438724,180.744993,170.487934,188.196448,508.823210
17,Haiti,333.275862,62.019893,58.007303,12.732276,389.662476
18,Philippines,1501.310345,29.944000,26.203414,563.620690,501.272379
19,Tanzania,40.646586,786.307663,789.624797,75.256400,815.616210
20,Zambia,0.570069,42.855127,42.649610,0.068966,43.185197
21,Benin,0.000000,0.063966,0.063966,0.000000,0.063966
22,Cameroon,79.787897,795.942577,729.091645,181.943069,770.235855
23,Central African Republic,13.560000,97.366456,92.851631,16.384690,104.515079
24,Colombia,1388.097669,10953.061020,10926.738310,2327.965690,11926.601600
25,Costa Rica,370.238621,1683.603825,1654.757534,154.511034,2016.203052
26,CÃ´te d'Ivoire,224.850655,2640.989406,2593.019476,1027.788241,2658.525303
27,Democratic Republic of Congo,200.000000,438.641994,393.192238,34.143379,589.295686
28,El Salvador,229.725310,1542.671788,1480.002162,166.012759,1598.384334
29,Equatorial Guinea,0.000000,0.881828,0.638103,0.351724,0.580517
30,Ethiopia,2529.034483,2257.551574,2326.651490,2044.586207,4880.789417
31,Gabon,0.628241,1.060177,0.980383,0.599517,1.539900
32,Ghana,5.661379,30.461676,30.591972,12.370448,36.184386
33,Guatemala,326.034483,3590.512097,3614.588628,106.695931,3910.381731
34,Guinea,48.120690,225.830006,226.816866,26.413828,274.420314
35,Guyana,4.978759,1.305947,1.318552,0.000000,5.872314
36,Honduras,259.109586,3194.853765,3355.469269,153.354034,3636.434097
37,India,1153.137931,3777.195530,3896.537276,1058.068966,4552.609690
38,Jamaica,10.429897,19.966535,19.785914,8.654621,30.215810
39,Kenya,52.241379,989.200405,959.627121,203.535276,987.167362
40,Lao People's Democratic Republic,85.379310,243.108008,250.530421,0.655172,300.162076
41,Liberia,4.793103,4.361228,3.655679,0.000000,8.448783
42,Mexico,1749.517241,3143.855086,3109.249886,598.732759,4376.146438
43,Nepal,0.000000,0.903943,1.277603,0.031034,0.856041
44,Nicaragua,165.000172,1270.768988,1329.936879,86.193345,1467.185017
45,Nigeria,39.275862,6.434295,6.366579,0.275862,45.642441
46,Panama,68.331586,91.047137,89.761421,31.493793,157.679214
47,Sierra Leone,5.620690,50.098006,46.814148,14.310345,48.227941
48,Sri Lanka,32.298862,9.234620,9.165066,3.655172,41.119100
49,Thailand,669.310345,551.847711,521.790931,84.168414,944.273690
50,Togo,1.236793,165.468715,161.636517,24.680310,161.011238
51,Trinidad & Tobago,11.775862,3.671784,2.813786,0.484241,14.417234
52,Uganda,154.928966,3080.789345,3132.876862,1049.680310,3211.943759
53,Venezuela,1327.337931,136.791798,127.478103,131.639483,1121.038724
54,Viet Nam,1016.050759,13048.102878,13701.263769,1483.241414,15156.584548
55,Yemen,67.689655,57.718630,57.641045,1.655172,107.300966

In [15]:
get_means(dfs[0]).merge(get_means(dfs[1]), on='country')

                             country  domestic_consumption       exports
0                             Angola             25.689655     24.115531
1   Bolivia (Plurinational State of)             41.103448     78.384152
2                             Brazil          15234.310345  25706.195606
3                            Burundi              1.891966    363.186423
4                            Ecuador            214.137931   1115.800914
5                          Indonesia           2662.137931   5878.047357
6                         Madagascar            325.405724    289.048949
7                             Malawi              1.310345     47.247465
8                   Papua New Guinea              2.004828   1015.455512
9                           Paraguay             19.482759     25.757542
10                              Peru            222.413793   2688.290420
11                            Rwanda              1.195379    316.250499
12                       Timor-Leste              0.152069     35.083247
13                          Zimbabwe              4.802276     78.112883
14                             Congo              2.977034      1.341862
15                              Cuba            213.244828     63.499287
16                Dominican Republic            356.438724    180.744993
17                             Haiti            333.275862     62.019893
18                       Philippines           1501.310345     29.944000
19                          Tanzania             40.646586    786.307663
20                            Zambia              0.570069     42.855127
21                             Benin              0.000000      0.063966
22                          Cameroon             79.787897    795.942577
23          Central African Republic             13.560000     97.366456
24                          Colombia           1388.097669  10953.061020
25                        Costa Rica            370.238621   1683.603825
26                     CÃ´te d'Ivoire            224.850655   2640.989406
27      Democratic Republic of Congo            200.000000    438.641994
28                       El Salvador            229.725310   1542.671788
29                 Equatorial Guinea              0.000000      0.881828
30                          Ethiopia           2529.034483   2257.551574
31                             Gabon              0.628241      1.060177
32                             Ghana              5.661379     30.461676
33                         Guatemala            326.034483   3590.512097
34                            Guinea             48.120690    225.830006
35                            Guyana              4.978759      1.305947
36                          Honduras            259.109586   3194.853765
37                             India           1153.137931   3777.195530
38                           Jamaica             10.429897     19.966535
39                             Kenya             52.241379    989.200405
40  Lao People's Democratic Republic             85.379310    243.108008
41                           Liberia              4.793103      4.361228
42                            Mexico           1749.517241   3143.855086
43                             Nepal              0.000000      0.903943
44                         Nicaragua            165.000172   1270.768988
45                           Nigeria             39.275862      6.434295
46                            Panama             68.331586     91.047137
47                      Sierra Leone              5.620690     50.098006
48                         Sri Lanka             32.298862      9.234620
49                          Thailand            669.310345    551.847711
50                              Togo              1.236793    165.468715
51                 Trinidad & Tobago             11.775862      3.671784
52                            Uganda            154.928966   3080.789345
53                         Venezuela           1327.337931    136.791798
54                          Viet Nam           1016.050759  13048.102878
55                             Yemen             67.689655     57.718630

In [18]:
df = data.copy()

In [19]:
# Drop country column
df = df.drop("country", axis=1)

In [20]:
# Split df into X and y
y = df["total_production"]
X = df.drop('total_production', axis=1)

In [21]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=1)

In [22]:
X_train

,domestic_consumption,exports,exports_crop_year,gross_opening_stocks
52,154.928966,3080.789345,3132.876862,1049.680310
35,4.978759,1.305947,1.318552,0.000000
26,224.850655,2640.989406,2593.019476,1027.788241
45,39.275862,6.434295,6.366579,0.275862
54,1016.050759,13048.102878,13701.263769,1483.241414
27,200.000000,438.641994,393.192238,34.143379
34,48.120690,225.830006,226.816866,26.413828
13,4.802276,78.112883,76.360955,18.070241
22,79.787897,795.942577,729.091645,181.943069
47,5.620690,50.098006,46.814148,14.310345
30,2529.034483,2257.551574,2326.651490,2044.586207
17,333.275862,62.019893,58.007303,12.732276
51,11.775862,3.671784,2.813786,0.484241
31,0.628241,1.060177,0.980383,0.599517
23,13.560000,97.366456,92.851631,16.384690
4,214.137931,1115.800914,1105.434110,108.592069
14,2.977034,1.341862,1.283931,1.931034
29,0.000000,0.881828,0.638103,0.351724
28,229.725310,1542.671788,1480.002162,166.012759
50,1.236793,165.468715,161.636517,24.680310
40,85.379310,243.108008,250.530421,0.655172
18,1501.310345,29.944000,26.203414,563.620690
55,67.689655,57.718630,57.641045,1.655172
20,0.570069,42.855127,42.649610,0.068966
25,370.238621,1683.603825,1654.757534,154.511034
6,325.405724,289.048949,280.822603,87.587000
7,1.310345,47.247465,46.095669,4.896552
53,1327.337931,136.791798,127.478103,131.639483
1,41.103448,78.384152,76.904748,7.237931
16,356.438724,180.744993,170.487934,188.196448
0,25.689655,24.115531,23.187083,42.068966
15,213.244828,63.499287,61.241072,78.068966
5,2662.137931,5878.047357,5879.061059,690.114655
11,1.195379,316.250499,312.973890,15.106690
9,19.482759,25.757542,20.850776,36.379310
8,2.004828,1015.455512,1015.019583,55.757928
12,0.152069,35.083247,35.722397,0.000000
43,0.000000,0.903943,1.277603,0.031034
37,1153.137931,3777.195530,3896.537276,1058.068966

In [23]:
y_train

52     3211.943759
35        5.872314
26     2658.525303
45       45.642441
54    15156.584548
27      589.295686
34      274.420314
13       75.645990
22      770.235855
47       48.227941
30     4880.789417
17      389.662476
51       14.417234
31        1.539900
23      104.515079
4      1076.504352
14        3.847172
29        0.580517
28     1598.384334
50      161.011238
40      300.162076
18      501.272379
55      107.300966
20       43.185197
25     2016.203052
6       587.719424
7        46.716359
53     1121.038724
1       116.146128
16      508.823210
0        45.256048
15      201.634176
5      8452.302438
11      309.893407
9        34.678362
8      1010.334755
12       35.874466
43        0.856041
37     4552.609690
Name: total_production, dtype: float64

In [25]:
# Scale X
scaler = StandardScaler()
scaler.fit(X_train)
X_train = pd.DataFrame(scaler.transform(X_train), index=X_train.index, columns=X_train.columns)
X_test = pd.DataFrame(scaler.transform(X_test), index=X_test.index, columns=X_test.columns)

In [26]:
X_train

    domestic_consumption   exports  exports_crop_year  gross_opening_stocks
52             -0.288283  0.892275           0.873300              1.747068
35             -0.521580 -0.437099          -0.426357             -0.515553
26             -0.179496  0.702419           0.649249              1.699879
45             -0.468220 -0.434885          -0.424262             -0.514958
54              1.051480  5.195041           5.259387              2.681623
27             -0.218160 -0.248307          -0.263722             -0.441956
34             -0.454459 -0.340175          -0.332771             -0.458617
13             -0.521855 -0.403943          -0.395213             -0.476602
22             -0.405190 -0.094064          -0.124317             -0.123369
47             -0.520582 -0.416036          -0.407476             -0.484707
30              3.405431  0.536894           0.538701              3.891621
17             -0.010805 -0.410890          -0.402830             -0.488108
51             -0.511005 -0.436078          -0.425737             -0.514509
31             -0.528349 -0.437205          -0.426498             -0.514261
23             -0.508229 -0.395631          -0.388369             -0.480235
4              -0.196163  0.044014           0.031872             -0.281479
14             -0.524695 -0.437084          -0.426372             -0.511391
29             -0.529326 -0.437282          -0.426640             -0.514795
28             -0.171912  0.228289           0.187325             -0.157707
50             -0.527402 -0.366232          -0.359822             -0.462354
40             -0.396490 -0.332716          -0.322930             -0.514141
18              1.806463 -0.424737          -0.416030              0.699350
55             -0.424013 -0.412747          -0.402982             -0.511985
20             -0.528439 -0.419163          -0.409204             -0.515404
25              0.046703  0.289128           0.259852             -0.182499
6              -0.023049 -0.312884          -0.310358             -0.326756
7              -0.527288 -0.417267          -0.407774             -0.504998
53              1.535791 -0.378612          -0.373999             -0.231800
1              -0.465376 -0.403826          -0.394988             -0.499952
16              0.025233 -0.359638          -0.356149             -0.109889
0              -0.489358 -0.427253          -0.417282             -0.424872
15             -0.197553 -0.410251          -0.401488             -0.347273
5               3.612517  2.099817           2.013020              0.972012
11             -0.527467 -0.301142          -0.297014             -0.482990
9              -0.499015 -0.426544          -0.418251             -0.437136
8              -0.526207  0.000697          -0.005652             -0.395365
12             -0.529090 -0.422518          -0.412079             -0.515553
43             -0.529326 -0.437273          -0.426374             -0.515486
37              1.264764  1.192905           1.190234              1.765150

### Training/Results

In [27]:
model = RandomForestRegressor()
model.fit(X_train, y_train)
print("Model trained.")

Model trained.

In [28]:
y_pred = model.predict(X_test)
rmse = np.sqrt(np.mean((y_test - y_pred)**2))
print("RMSE: {:.2f}".format(rmse))

RMSE: 7423.55

In [29]:
np.sum((y_test - y_test.mean())**2)

1579133979.5953665

In [30]:
np.sum((y_test - y_pred)**2)

936854270.5261929

In [33]:
r2 = 1 - (np.sum((y_test - y_pred)**2) / np.sum((y_test - y_test.mean())**2))

In [34]:
print("R^2: {:.5f}".format(r2))

R^2: 0.40673

In [35]:
model.score(X_test, y_test)

0.40672907895614396